{{- if and (and .Values.cloudflare.account .Values.cloudflare.tunnelId .Values.cloudflare.tunnelSecret) (not .Values.cloudflare.tunnelSecretSecretName) }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.generate.tunnelSecretSecretName" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.account | quote }},
      "TunnelID": {{ .Values.cloudflare.tunnelId | quote }},
      "TunnelSecret": {{ .Values.cloudflare.tunnelSecret | quote }}
    }
{{- end }}
---
{{- if and (and .Values.cloudflare.cert) (not .Values.cloudflare.certSecretName) }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.generate.certSecretName" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  cert.pem: {{ .Values.cloudflare.cert }}
{{- end }}