{{- if and (and .Values.cloudflare.token) (not .Values.cloudflare.tokenSecretName) }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.generate.token-secretname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.cloudflare.token }}
{{- end }}